#include "freertos/FreeRTOS.h"
#include <freertos/task.h>
#include "esp_wifi.h"
#include "esp_system.h"
#include "esp_event.h"
#include "esp_event_loop.h"
#include "nvs_flash.h"
#include "driver/gpio.h"
#include <driver/spi_master.h>
#include <esp_log.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "main.h"
#include "msg_type.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#include "bme280.h"

#include "sd_card.h"

#define SDA_PIN 25 // GPIO_NUM_15
#define SCL_PIN 22 // GPIO_NUM_2

#define TAG "MAIN"

#define TAG_BME280 "BME280"

//#define s8 int8_t
//#define u8 uint8_t
//#define s32 int32_t
//#define u32 uint32_t

#define true 1
#define false 0

void i2c_master_init()
{
	i2c_config_t i2c_config = {
		.mode = I2C_MODE_MASTER,
		.sda_io_num = SDA_PIN,
		.scl_io_num = SCL_PIN,
		.sda_pullup_en = GPIO_PULLUP_ENABLE,
		.scl_pullup_en = GPIO_PULLUP_ENABLE,
		.master.clk_speed = 1000000
	};
	i2c_param_config(I2C_NUM_0, &i2c_config);
	i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
}

s8 BME280_I2C_bus_write(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt)
{
	s32 iError = BME280_INIT_VALUE;

	esp_err_t espRc;
	i2c_cmd_handle_t cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_WRITE, true);

	i2c_master_write_byte(cmd, reg_addr, true);
	i2c_master_write(cmd, reg_data, cnt, true);
	i2c_master_stop(cmd);

	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		iError = SUCCESS;
	} else {
		iError = FAIL;
	}
	i2c_cmd_link_delete(cmd);

	return (s8)iError;
}

s8 BME280_I2C_bus_read(u8 dev_addr, u8 reg_addr, u8 *reg_data, u8 cnt)
{
	s32 iError = BME280_INIT_VALUE;
	esp_err_t espRc;

	i2c_cmd_handle_t cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, reg_addr, true);

	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (dev_addr << 1) | I2C_MASTER_READ, true);

	if (cnt > 1) {
		i2c_master_read(cmd, reg_data, cnt-1, I2C_MASTER_ACK);
	}
	i2c_master_read_byte(cmd, reg_data+cnt-1, I2C_MASTER_NACK);
	i2c_master_stop(cmd);

	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		iError = SUCCESS;
	} else {
		iError = FAIL;
	}

	i2c_cmd_link_delete(cmd);

	return (s8)iError;
}

void BME280_delay_msek(u32 msek)
{
	vTaskDelay(msek/portTICK_PERIOD_MS);
}

void task_bme280_normal_mode(void *pvParameters)
{
  int tmp = *((int * )pvParameters);
  ESP_LOGI(TAG_BME280, "Parameter is :%d", tmp );
	struct bme280_t bme280 = {
		.bus_write = BME280_I2C_bus_write,
		.bus_read = BME280_I2C_bus_read,
		.dev_addr = BME280_I2C_ADDRESS1,
		.delay_msec = BME280_delay_msek
	};

	s32 com_rslt;
	s32 v_uncomp_pressure_s32;
	s32 v_uncomp_temperature_s32;
	s32 v_uncomp_humidity_s32;

	com_rslt = bme280_init(&bme280);

	com_rslt += bme280_set_oversamp_pressure(BME280_OVERSAMP_16X);
	com_rslt += bme280_set_oversamp_temperature(BME280_OVERSAMP_2X);
	com_rslt += bme280_set_oversamp_humidity(BME280_OVERSAMP_1X);

	com_rslt += bme280_set_standby_durn(BME280_STANDBY_TIME_1_MS);
	com_rslt += bme280_set_filter(BME280_FILTER_COEFF_16);

	com_rslt += bme280_set_power_mode(BME280_NORMAL_MODE);
	if (com_rslt == SUCCESS) {
		while( (*((int *)pvParameters) ) == 1) {
			vTaskDelay(100/portTICK_PERIOD_MS);

			com_rslt = bme280_read_uncomp_pressure_temperature_humidity(
				&v_uncomp_pressure_s32, &v_uncomp_temperature_s32, &v_uncomp_humidity_s32);

			if (com_rslt == SUCCESS) {
				ESP_LOGI(TAG_BME280, "%.2f degC / %.3f hPa / %.3f %%",
					bme280_compensate_temperature_double(v_uncomp_temperature_s32),
					bme280_compensate_pressure_double(v_uncomp_pressure_s32)/100, // Pa -> hPa
					bme280_compensate_humidity_double(v_uncomp_humidity_s32));

				bme280Info bInfo = {
						.temperature = bme280_compensate_temperature_double(v_uncomp_temperature_s32),
						.pressure = bme280_compensate_pressure_double(v_uncomp_pressure_s32)/100,
						.humidity = bme280_compensate_humidity_double(v_uncomp_humidity_s32)
				};
				xQueueSendToBack(bme280_queue, (void *)(&bInfo), (TickType_t)0);
			} else {
				ESP_LOGE(TAG_BME280, "measure error. code: %d", com_rslt);
			}
		}
	} else {
		ESP_LOGE(TAG_BME280, "init or setting error. code: %d", com_rslt);
	}

	ESP_LOGI(TAG_BME280, "bme280 Task get terminated");
	vTaskDelete(NULL);
}

void task_bme280_forced_mode(void *ignore) {
	struct bme280_t bme280 = {
		.bus_write = BME280_I2C_bus_write,
		.bus_read = BME280_I2C_bus_read,
//		.dev_addr = BME280_I2C_ADDRESS2,
		.dev_addr = BME280_I2C_ADDRESS1,
		.delay_msec = BME280_delay_msek
	};

	s32 com_rslt;
	s32 v_uncomp_pressure_s32;
	s32 v_uncomp_temperature_s32;
	s32 v_uncomp_humidity_s32;

	com_rslt = bme280_init(&bme280);

	com_rslt += bme280_set_oversamp_pressure(BME280_OVERSAMP_1X);
	com_rslt += bme280_set_oversamp_temperature(BME280_OVERSAMP_1X);
	com_rslt += bme280_set_oversamp_humidity(BME280_OVERSAMP_1X);

	com_rslt += bme280_set_filter(BME280_FILTER_COEFF_OFF);
	if (com_rslt == SUCCESS) {
		while(true) {
			com_rslt = bme280_get_forced_uncomp_pressure_temperature_humidity(
				&v_uncomp_pressure_s32, &v_uncomp_temperature_s32, &v_uncomp_humidity_s32);

			if (com_rslt == SUCCESS) {
				ESP_LOGI(TAG_BME280, "%.2f degC / %.3f hPa / %.3f %%",
					bme280_compensate_temperature_double(v_uncomp_temperature_s32),
					bme280_compensate_pressure_double(v_uncomp_pressure_s32)/100, // Pa -> hPa
					bme280_compensate_humidity_double(v_uncomp_humidity_s32));
			} else {
				ESP_LOGE(TAG_BME280, "measure error. code: %d", com_rslt);
			}
		}
	} else {
		ESP_LOGE(TAG_BME280, "init or setting error. code: %d", com_rslt);
	}

	vTaskDelete(NULL);
}



//static char tag[] = "mpcd";

extern void task_test_pcd8544(void *ignore);
extern void sd_card_task(void *ignore);
//extern void task_scroll_text(void *ignore);
extern void gps_clock_task(void *pvParameters);

// On board LED for Blink is on GPIO 21
#define LCD_LIGHT 5 // LCD Back Light
#define BTN 19      // Button on front panel



void app_main(void)
{
  bme280_queue = xQueueCreate(10, sizeof(bme280Info));
  if(bme280_queue != 0) {
	  ESP_LOGI(TAG, "bme280 queue inited");
  } else {
	  ESP_LOGD(TAG, "bme280 queue can't init");
  }
	//xTaskCreatePinnedToCore(&task_scroll_text, "task_simple_tests_pcd8544", 8048, NULL, 5, NULL, 0);
  i2c_master_init();
//  TaskHandle_t xHandle_bme280;
  int loopholder_bme280 = 1;
  int loopholder_display = 1;
  xTaskCreate(&task_bme280_normal_mode, "bme280_normal_mode",  2048, &loopholder_bme280, 6, NULL);
//  xTaskCreate(gps_clock_task, "task_gps", 4096, NULL, 5, NULL); // Comment back if I got both SD & Display works together
//  xTaskCreate(&sd_card_task, "sd_card_task", 8048, NULL, 5, NULL); // Remove this task when test SD card works correctly
  xTaskCreate(&task_test_pcd8544, "task_pcd8544_display", 8048, &loopholder_display, 5, NULL);
//  xTaskCreate( vTaskCode, "NAME", STACK_SIZE, NULL, tskIDLE_PRIORITY, &xHandle );

  gpio_pad_select_gpio(LCD_LIGHT);
  gpio_set_direction(LCD_LIGHT, GPIO_MODE_OUTPUT);
  gpio_set_level(LCD_LIGHT, 1);

  // Button read snippet!
  gpio_pad_select_gpio(BTN);
  gpio_set_direction(BTN, GPIO_MODE_INPUT);
  gpio_pad_select_gpio(LCD_LIGHT);
  gpio_set_direction(LCD_LIGHT, GPIO_MODE_OUTPUT);
  int btn_old = 0;
  int btn_now = 0;
  while(1) {
    btn_now = gpio_get_level(BTN);
//    ESP_LOGI(TAG, "BTN: %d", btn_now);
    if(btn_now != btn_old){
//      ESP_LOGI(TAG, "Get New State");
      btn_old = btn_now;
      if(btn_now == 1){
        ESP_LOGI(TAG, "BTN get pressed down.");
        // TODO: Here I stop temperature reading Task
//        vTaskDelete( xHandle_bme280 ); // TODO: free in this task located heap memory
        loopholder_bme280 = 0; // This will cause the bme280 task go out of its while loop.
        // TODO: Here I stop Display Task
        loopholder_display = 0;
        // TODO: Here I Start SD Card Task, write Hello to the file
        // TODO: Here I read the right now coordinate to the SD Card
      }
    } else {
//      ESP_LOGI(TAG, "Old State");
    }
    vTaskDelay(100 / portTICK_PERIOD_MS);
  }

  printf("the damme esp32's main reach end!\n");
}

